/*
 * Forem API V1
 *
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Article : Representation of an Article to be created/updated

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Article {
    #[serde(rename = "article", skip_serializing_if = "Option::is_none")]
    pub article: Option<Box<crate::models::ArticleArticle>>,
}

impl Article {
    /// Representation of an Article to be created/updated
    pub fn new() -> Article {
        Article { article: None }
    }
}
