/*
 * Forem API V1
 *
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ArticleArticle {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "body_markdown", skip_serializing_if = "Option::is_none")]
    pub body_markdown: Option<String>,
    #[serde(rename = "published", skip_serializing_if = "Option::is_none")]
    pub published: Option<bool>,
    #[serde(rename = "series", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub series: Option<Option<String>>,
    #[serde(rename = "main_image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub main_image: Option<Option<String>>,
    #[serde(rename = "canonical_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub canonical_url: Option<Option<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    #[serde(rename = "organization_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<Option<i32>>,
}

impl ArticleArticle {
    pub fn new() -> ArticleArticle {
        ArticleArticle {
            title: None,
            body_markdown: None,
            published: None,
            series: None,
            main_image: None,
            canonical_url: None,
            description: None,
            tags: None,
            organization_id: None,
        }
    }
}


