/*
 * Forem API V1
 *
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetFollowers200ResponseInner : A follower



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFollowers200ResponseInner {
    /// user_follower by default
    #[serde(rename = "type_of", skip_serializing_if = "Option::is_none")]
    pub type_of: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The follower's user id
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The follower's name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A path to the follower's profile
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Profile image (640x640)
    #[serde(rename = "profile_image", skip_serializing_if = "Option::is_none")]
    pub profile_image: Option<String>,
}

impl GetFollowers200ResponseInner {
    /// A follower
    pub fn new() -> GetFollowers200ResponseInner {
        GetFollowers200ResponseInner {
            type_of: None,
            id: None,
            user_id: None,
            name: None,
            path: None,
            profile_image: None,
        }
    }
}


