/*
 * Forem API V1
 *
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SharedPodcast : The podcast that the resource belongs to



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SharedPodcast {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Podcast image url
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
}

impl SharedPodcast {
    /// The podcast that the resource belongs to
    pub fn new() -> SharedPodcast {
        SharedPodcast {
            title: None,
            slug: None,
            image_url: None,
        }
    }
}


