//!
//! As per <https://developers.forem.com/api>:
//!
//! # API  
//!   
//! There are two versions of the API: version 0 and version 1. All V0 endpoints are available in V1: we will be adding V1 documentation for these endpoints in the future. Right now we recommend calling V0 endpoints with accept and api-key headers.  
//! * Note: This crate was generated using V1 *
//! //!
//! ## Version 0  
//! This is the legacy API. It is deprecated and will be removed in a future release. Clients can continue to use it as is, but we recommend using the version 1 API.  
//!
//! ## Version 1 (this crate was generated from this version)  
//! This is the current version of the API. It is the recommended way to interact with Forem. Version 1 requires clients to use an accept header, and many endpoints (but not all) require api-key header.  
//! 
//! The accept header must be set to application/vnd.forem.api-v1+json. The api-key header must be set to the API key for the user. This API key can be generated by the user via their settings page in Forem.  
//!
//! Access Forem articles, users and other resources via API. For a real-world example of Forem in action, check out DEV. All endpoints can be accessed with the 'api-key' header and a accept header, but some of them are accessible publicly without authentication.  
//! ## Note on Dates and Date Times
//! Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
//! 
#[macro_use]
extern crate serde_derive;

extern crate reqwest;
extern crate serde;
extern crate serde_json;
extern crate url;

pub mod apis;
pub mod models;
